const Nationalities = [
    { "textSk": "", "textEn": "", "value": null },
    { "textSk": "Afghánska", "textEn": "Afghan", "value": 1 },
    { "textSk": "Albánska", "textEn": "Albanian", "value": 2 },
    { "textSk": "Alžírska", "textEn": "Algerian", "value": 3 },
    { "textSk": "Americká", "textEn": "American", "value": 4 },
    { "textSk": "Andorrská", "textEn": "Andorran", "value": 5 },
    { "textSk": "Angolská", "textEn": "Angolan", "value": 6 },
    { "textSk": "Argentínska", "textEn": "Argentinian", "value": 7 },
    { "textSk": "Arménska", "textEn": "Armenian", "value": 8 },
    { "textSk": "Austrálska", "textEn": "Australian", "value": 9 },
    { "textSk": "Rakúska", "textEn": "Austrian", "value": 10 },
    { "textSk": "Azerbajdžanská", "textEn": "Azerbaijani", "value": 11 },
    { "textSk": "Bahamská", "textEn": "Bahamian", "value": 12 },
    { "textSk": "Bahrajnská", "textEn": "Bahraini", "value": 13 },
    { "textSk": "Bangladéšska", "textEn": "Bangladeshi", "value": 14 },
    { "textSk": "Barbadoská", "textEn": "Barbadian", "value": 15 },
    { "textSk": "Belgická", "textEn": "Belgian", "value": 16 },
    { "textSk": "Belizská", "textEn": "Belizean", "value": 17 },
    { "textSk": "Bieloruská", "textEn": "Belarusian", "value": 18 },
    { "textSk": "Beninská", "textEn": "Beninese", "value": 19 },
    { "textSk": "Bhutánska", "textEn": "Bhutanese", "value": 20 },
    { "textSk": "Bolívijská", "textEn": "Bolivian", "value": 21 },
    { "textSk": "Bosnianska", "textEn": "Bosnian", "value": 22 },
    { "textSk": "Botswanská", "textEn": "Botswanan", "value": 23 },
    { "textSk": "Brazílska", "textEn": "Brazilian", "value": 24 },
    { "textSk": "Britská", "textEn": "British", "value": 25 },
    { "textSk": "Brunejská", "textEn": "Bruneian", "value": 26 },
    { "textSk": "Bulharská", "textEn": "Bulgarian", "value": 27 },
    { "textSk": "Burkinafská", "textEn": "Burkinabe", "value": 28 },
    { "textSk": "Burundská", "textEn": "Burundian", "value": 29 },
    { "textSk": "Kambodžská", "textEn": "Cambodian", "value": 30 },
    { "textSk": "Kamerunská", "textEn": "Cameroonian", "value": 31 },
    { "textSk": "Kanadská", "textEn": "Canadian", "value": 32 },
    { "textSk": "Kapverdská", "textEn": "Cape Verdean", "value": 33 },
    { "textSk": "Stredoafrická", "textEn": "Central African", "value": 34 },
    { "textSk": "Čadská", "textEn": "Chadian", "value": 35 },
    { "textSk": "Čilská", "textEn": "Chilean", "value": 36 },
    { "textSk": "Čínska", "textEn": "Chinese", "value": 37 },
    { "textSk": "Kolumbijská", "textEn": "Colombian", "value": 38 },
    { "textSk": "Komorská", "textEn": "Comorian", "value": 39 },
    { "textSk": "Konžská", "textEn": "Congolese", "value": 40 },
    { "textSk": "Kostarická", "textEn": "Costa Rican", "value": 41 },
    { "textSk": "Chorvátska", "textEn": "Croatian", "value": 42 },
    { "textSk": "Kubánska", "textEn": "Cuban", "value": 43 },
    { "textSk": "Cyperská", "textEn": "Cypriot", "value": 44 },
    { "textSk": "Česká", "textEn": "Czech", "value": 45 },
    { "textSk": "Dánska", "textEn": "Danish", "value": 46 },
    { "textSk": "Džibutská", "textEn": "Djiboutian", "value": 47 },
    { "textSk": "Dominická", "textEn": "Dominican", "value": 48 },
    { "textSk": "Východotimorská", "textEn": "East Timorese", "value": 49 },
    { "textSk": "Ekvádorská", "textEn": "Ecuadorian", "value": 50 },
    { "textSk": "Egyptská", "textEn": "Egyptian", "value": 51 },
    { "textSk": "Salvadorská", "textEn": "Salvadoran", "value": 52 },
    { "textSk": "Rovníkovoguinejská", "textEn": "Equatorial Guinean", "value": 53 },
    { "textSk": "Eritrejská", "textEn": "Eritrean", "value": 54 },
    { "textSk": "Estónska", "textEn": "Estonian", "value": 55 },
    { "textSk": "Etiópska", "textEn": "Ethiopian", "value": 56 },
    { "textSk": "Fidžijská", "textEn": "Fijian", "value": 57 },
    { "textSk": "Fínska", "textEn": "Finnish", "value": 58 },
    { "textSk": "Francúzska", "textEn": "French", "value": 59 },
    { "textSk": "Gabonská", "textEn": "Gabonese", "value": 60 },
    { "textSk": "Gambijská", "textEn": "Gambian", "value": 61 },
    { "textSk": "Gruzínska", "textEn": "Georgian", "value": 62 },
    { "textSk": "Nemecká", "textEn": "German", "value": 63 },
    { "textSk": "Ghanská", "textEn": "Ghanaian", "value": 64 },
    { "textSk": "Grécka", "textEn": "Greek", "value": 65 },
    { "textSk": "Grenadská", "textEn": "Grenadian", "value": 66 },
    { "textSk": "Guatemalská", "textEn": "Guatemalan", "value": 67 },
    { "textSk": "Guinejská", "textEn": "Guinean", "value": 68 },
    { "textSk": "Guinejsko-bissauská", "textEn": "Bissau-Guinean", "value": 69 },
    { "textSk": "Guyanská", "textEn": "Guyanese", "value": 70 },
    { "textSk": "Haitská", "textEn": "Haitian", "value": 71 },
    { "textSk": "Honduraská", "textEn": "Honduran", "value": 72 },
    { "textSk": "Maďarská", "textEn": "Hungarian", "value": 73 },
    { "textSk": "Islandská", "textEn": "Icelandic", "value": 74 },
    { "textSk": "Indická", "textEn": "Indian", "value": 75 },
    { "textSk": "Indonézska", "textEn": "Indonesian", "value": 76 },
    { "textSk": "Iránska", "textEn": "Iranian", "value": 77 },
    { "textSk": "Iracká", "textEn": "Iraqi", "value": 78 },
    { "textSk": "Írska", "textEn": "Irish", "value": 79 },
    { "textSk": "Izraelská", "textEn": "Israeli", "value": 80 },
    { "textSk": "Talianska", "textEn": "Italian", "value": 81 },
    { "textSk": "Pobrežia Slonoviny", "textEn": "Ivorian", "value": 82 },
    { "textSk": "Jamajská", "textEn": "Jamaican", "value": 83 },
    { "textSk": "Japonská", "textEn": "Japanese", "value": 84 },
    { "textSk": "Jordánska", "textEn": "Jordanian", "value": 85 },
    { "textSk": "Kazašská", "textEn": "Kazakh", "value": 86 },
    { "textSk": "Kenská", "textEn": "Kenyan", "value": 87 },
    { "textSk": "Kiribatská", "textEn": "Kiribati", "value": 88 },
    { "textSk": "Kórejská (Južná)", "textEn": "South Korean", "value": 89 },
    { "textSk": "Kórejská (Severná)", "textEn": "North Korean", "value": 90 },
    { "textSk": "Kuvajtská", "textEn": "Kuwaiti", "value": 91 },
    { "textSk": "Kirgizská", "textEn": "Kyrgyz", "value": 92 },
    { "textSk": "Laoská", "textEn": "Laotian", "value": 93 },
    { "textSk": "Lotyšská", "textEn": "Latvian", "value": 94 },
    { "textSk": "Libanonská", "textEn": "Lebanese", "value": 95 },
    { "textSk": "Lesothská", "textEn": "Basotho", "value": 96 },
    { "textSk": "Libérijská", "textEn": "Liberian", "value": 97 },
    { "textSk": "Líbyjská", "textEn": "Libyan", "value": 98 },
    { "textSk": "Lichtenštajnská", "textEn": "Liechtensteiner", "value": 99 },
    { "textSk": "Litovská", "textEn": "Lithuanian", "value": 100 },
    { "textSk": "Luxemburská", "textEn": "Luxembourgish", "value": 101 },
    { "textSk": "Madagaskarská", "textEn": "Malagasy", "value": 102 },
    { "textSk": "Malawijská", "textEn": "Malawian", "value": 103 },
    { "textSk": "Malajzijská", "textEn": "Malaysian", "value": 104 },
    { "textSk": "Maldivská", "textEn": "Maldivian", "value": 105 },
    { "textSk": "Mali", "textEn": "Malian", "value": 106 },
    { "textSk": "Maltská", "textEn": "Maltese", "value": 107 },
    { "textSk": "Marshallská", "textEn": "Marshallese", "value": 108 },
    { "textSk": "Mauritánska", "textEn": "Mauritanian", "value": 109 },
    { "textSk": "Maurícijská", "textEn": "Mauritian", "value": 110 },
    { "textSk": "Mexická", "textEn": "Mexican", "value": 111 },
    { "textSk": "Mikronézska", "textEn": "Micronesian", "value": 112 },
    { "textSk": "Moldavská", "textEn": "Moldovan", "value": 113 },
    { "textSk": "Monacká", "textEn": "Monegasque", "value": 114 },
    { "textSk": "Mongolská", "textEn": "Mongolian", "value": 115 },
    { "textSk": "Čiernohorská", "textEn": "Montenegrin", "value": 116 },
    { "textSk": "Marocká", "textEn": "Moroccan", "value": 117 },
    { "textSk": "Mozambická", "textEn": "Mozambican", "value": 118 },
    { "textSk": "Mjanmarská", "textEn": "Burmese", "value": 119 },
    { "textSk": "Namíbijská", "textEn": "Namibian", "value": 120 },
    { "textSk": "Nauruská", "textEn": "Nauruan", "value": 121 },
    { "textSk": "Nepálska", "textEn": "Nepalese", "value": 122 },
    { "textSk": "Holandská", "textEn": "Dutch", "value": 123 },
    { "textSk": "Novozélandská", "textEn": "New Zealander", "value": 124 },
    { "textSk": "Nikaragujská", "textEn": "Nicaraguan", "value": 125 },
    { "textSk": "Nigerská", "textEn": "Nigerien", "value": 126 },
    { "textSk": "Nigérijská", "textEn": "Nigerian", "value": 127 },
    { "textSk": "Severomacedónska", "textEn": "North Macedonian", "value": 128 },
    { "textSk": "Nórska", "textEn": "Norwegian", "value": 129 },
    { "textSk": "Ománska", "textEn": "Omani", "value": 130 },
    { "textSk": "Pakistanská", "textEn": "Pakistani", "value": 131 },
    { "textSk": "Palauanská", "textEn": "Palauan", "value": 132 },
    { "textSk": "Panamská", "textEn": "Panamanian", "value": 133 },
    { "textSk": "Papua-novoguinejská", "textEn": "Papua New Guinean", "value": 134 },
    { "textSk": "Paraguajská", "textEn": "Paraguayan", "value": 135 },
    { "textSk": "Peruánska", "textEn": "Peruvian", "value": 136 },
    { "textSk": "Filipínska", "textEn": "Filipino", "value": 137 },
    { "textSk": "Poľská", "textEn": "Polish", "value": 138 },
    { "textSk": "Portugalská", "textEn": "Portuguese", "value": 139 },
    { "textSk": "Katar", "textEn": "Qatari", "value": 140 },
    { "textSk": "Rumunská", "textEn": "Romanian", "value": 141 },
    { "textSk": "Ruská", "textEn": "Russian", "value": 142 },
    { "textSk": "Rwandská", "textEn": "Rwandan", "value": 143 },
    { "textSk": "Svätoluciánska", "textEn": "Saint Lucian", "value": 144 },
    { "textSk": "Svätovincentská", "textEn": "Saint Vincentian", "value": 145 },
    { "textSk": "Samoánska", "textEn": "Samoan", "value": 146 },
    { "textSk": "Sanmarínska", "textEn": "Sammarinese", "value": 147 },
    { "textSk": "Saudskoarabská", "textEn": "Saudi Arabian", "value": 148 },
    { "textSk": "Senegalská", "textEn": "Senegalese", "value": 149 },
    { "textSk": "Srbská", "textEn": "Serbian", "value": 150 },
    { "textSk": "Seychelská", "textEn": "Seychellois", "value": 151 },
    { "textSk": "Sierraleonská", "textEn": "Sierra Leonean", "value": 152 },
    { "textSk": "Singapurská", "textEn": "Singaporean", "value": 153 },
    { "textSk": "Slovenská", "textEn": "Slovak", "value": 154 },
    { "textSk": "Slovinská", "textEn": "Slovenian", "value": 155 },
    { "textSk": "Šalamúnska", "textEn": "Solomon Islander", "value": 156 },
    { "textSk": "Somálska", "textEn": "Somali", "value": 157 },
    { "textSk": "Juhoafrická", "textEn": "South African", "value": 158 },
    { "textSk": "Juhosudánska", "textEn": "South Sudanese", "value": 159 },
    { "textSk": "Španielska", "textEn": "Spanish", "value": 160 },
    { "textSk": "Srílanská", "textEn": "Sri Lankan", "value": 161 },
    { "textSk": "Sudánska", "textEn": "Sudanese", "value": 162 },
    { "textSk": "Surinamská", "textEn": "Surinamese", "value": 163 },
    { "textSk": "Svazijská", "textEn": "Swazi", "value": 164 },
    { "textSk": "Švédska", "textEn": "Swedish", "value": 165 },
    { "textSk": "Švajčiarska", "textEn": "Swiss", "value": 166 },
    { "textSk": "Sýrska", "textEn": "Syrian", "value": 167 },
    { "textSk": "Tadžická", "textEn": "Tajik", "value": 168 },
    { "textSk": "Tanzánijská", "textEn": "Tanzanian", "value": 169 },
    { "textSk": "Thajská", "textEn": "Thai", "value": 170 },
    { "textSk": "Togská", "textEn": "Togolese", "value": 171 },
    { "textSk": "Tongská", "textEn": "Tongan", "value": 172 },
    { "textSk": "Trinidadsko-tobažská", "textEn": "Trinidadian and Tobagonian", "value": 173 },
    { "textSk": "Tuniská", "textEn": "Tunisian", "value": 174 },
    { "textSk": "Turecká", "textEn": "Turkish", "value": 175 },
    { "textSk": "Turkménska", "textEn": "Turkmen", "value": 176 },
    { "textSk": "Tuvalská", "textEn": "Tuvaluan", "value": 177 },
    { "textSk": "Ugandská", "textEn": "Ugandan", "value": 178 },
    { "textSk": "Ukrajinská", "textEn": "Ukrainian", "value": 179 },
    { "textSk": "Spojených arabských emirátov", "textEn": "Emirati", "value": 180 },
    { "textSk": "Uruguajská", "textEn": "Uruguayan", "value": 181 },
    { "textSk": "Uzbecká", "textEn": "Uzbek", "value": 182 },
    { "textSk": "Vanuatská", "textEn": "Ni-Vanuatu", "value": 183 },
    { "textSk": "Venezuelská", "textEn": "Venezuelan", "value": 184 },
    { "textSk": "Vietnamská", "textEn": "Vietnamese", "value": 185 },
    { "textSk": "Jemenská", "textEn": "Yemeni", "value": 186 },
    { "textSk": "Zambijská", "textEn": "Zambian", "value": 187 },
    { "textSk": "Zimbabwianska", "textEn": "Zimbabwean", "value": 188 },
    { "textSk": "Kosovská", "textEn": "Kosovar", "value": 189 },
    { "textSk": "Palestínska", "textEn": "Palestinian", "value": 190 },
    { "textSk": "Taiwanská", "textEn": "Taiwanese", "value": 191 },
    { "textSk": "Vatikánska", "textEn": "Vatican", "value": 192 },
    { "textSk": "Karibská", "textEn": "Caribbean", "value": 193 },
    { "textSk": "Neurčená", "textEn": "Unspecified", "value": 194 }
]

export default Nationalities